# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlannerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlannerApp
	pod 'SwiftLint', '~> 0.27'
	pod 'KeychainSwift'
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'
	pod 'FirebaseFirestoreSwift'
end
